import fs from "node:fs";

const source = fs.readFileSync(new URL("../src/index.js", import.meta.url), "utf8");
const banner = "// Generated by npm run build. Commit this file for GitHub Actions.\n";
fs.writeFileSync(new URL("../dist/index.js", import.meta.url), `${banner}${source}`, "utf8");
